#!/bin/bash

if [ ! -f "${USERDATA}/RssFeeds.xml" ]; then
   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    First run detected. Configure advanced settings"

#   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Enable debug logging"
#   sed -i "/^<advancedsettings>$/ a<loglevel>1<\/loglevel>" "${USERDATA}/advancedsettings.xml"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Configure Kodi video database host, user and password"
   sed -i "/^<videodatabase>$/,/^<\/videodatabase>$/ s%^<host>.*<\/host>*%<host>mariadb<\/host>%" "${USERDATA}/advancedsettings.xml"
   sed -i "/^<videodatabase>$/,/^<\/videodatabase>$/ s%^<user>.*<\/user>*%<user>kodi<\/user>%" "${USERDATA}/advancedsettings.xml"
   sed -i "/^<videodatabase>$/,/^<\/videodatabase>$/ s%^<pass>.*<\/pass>*%<pass>${KODIPASSWORD}<\/pass>%" "${USERDATA}/advancedsettings.xml"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Configure Kodi music database host, user and password"
   sed -i "/^<musicdatabase>$/,/^<\/musicdatabase>$/ s%^<host>.*<\/host>*%<host>mariadb<\/host>%" "${USERDATA}/advancedsettings.xml"
   sed -i "/^<musicdatabase>$/,/^<\/musicdatabase>$/ s%^<user>.*<\/user>*%<user>kodi<\/user>%" "${USERDATA}/advancedsettings.xml"
   sed -i "/^<musicdatabase>$/,/^<\/musicdatabase>$/ s%^<pass>.*<\/pass>*%<pass>${KODIPASSWORD}<\/pass>%" "${USERDATA}/advancedsettings.xml"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Enable library cleaning"
   sed -i "/^<videolibrary>$/ a<cleanonupdate>true<\/cleanonupdate>" "${USERDATA}/advancedsettings.xml"
   sed -i "/^<musiclibrary>$/ a<cleanonupdate>true<\/cleanonupdate>" "${USERDATA}/advancedsettings.xml"
fi