#!/bin/bash

CONFIGDIR="/config"

if [ ! -d "${CONFIGDIR}/.kodi/addons/packages" ]; then
   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    First run detected Download required addons"

   mkdir -p "${CONFIGDIR}/.kodi/addons/packages"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Download python-dateutil addon"
   LATESTDATEUTIL="$(curl -sX GET "http://mirrors.kodi.tv/addons/leia/script.module.dateutil/" | awk '/dateutil/{print $4}' FS='"' | grep -v "^$" | tail -n1)"
   curl -so "${CONFIGDIR}/.kodi/addons/packages/${LATESTDATEUTIL}" -L "http://mirrors.kodi.tv/addons/leia/script.module.dateutil/${LATESTDATEUTIL}"
   unzip -q "${CONFIGDIR}/.kodi/addons/packages/${LATESTDATEUTIL}" -d "${CONFIGDIR}/.kodi/addons"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Download future addon"
   LATESTFUTURE="$(curl -sX GET "http://mirrors.kodi.tv/addons/leia/script.module.future/" | awk '/future/{print $4}' FS='"' | grep -v "^$" | tail -n1)"
   curl -so "${CONFIGDIR}/.kodi/addons/packages/${LATESTFUTURE}" -L "http://mirrors.kodi.tv/addons/leia/script.module.future/${LATESTFUTURE}"
   unzip -q "${CONFIGDIR}/.kodi/addons/packages/${LATESTFUTURE}" -d "${CONFIGDIR}/.kodi/addons"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Download six addon"
   LATESTSIX="$(curl -sX GET "http://mirrors.kodi.tv/addons/leia/script.module.six/" | awk '/six/{print $4}' FS='"' | grep -v "^$" | tail -n1)"
   curl -so "${CONFIGDIR}/.kodi/addons/packages/${LATESTSIX}" -L "http://mirrors.kodi.tv/addons/leia/script.module.six/${LATESTSIX}"
   unzip -q "${CONFIGDIR}/.kodi/addons/packages/${LATESTSIX}" -d "${CONFIGDIR}/.kodi/addons"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Download kodi-six addon"
   LATESTKODISIX="$(curl -sX GET "http://mirrors.kodi.tv/addons/leia/script.module.kodi-six/" | awk '/kodi-six/{print $4}' FS='"' | grep -v "^$" | tail -n1)"
   curl -so "${CONFIGDIR}/.kodi/addons/packages/${LATESTKODISIX}" -L "http://mirrors.kodi.tv/addons/leia/script.module.kodi-six/${LATESTKODISIX}"
   unzip -q "${CONFIGDIR}/.kodi/addons/packages/${LATESTKODISIX}" -d "${CONFIGDIR}/.kodi/addons"

   echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Download library auto-update addon"
   LATESTLIBRARYAUTOUPDATE="$(curl -sX GET "http://mirrors.kodi.tv/addons/leia/service.libraryautoupdate/" | awk '/libraryautoupdate/{print $4}' FS='"' | grep -v "^$" | tail -n1)"
   curl -so "${CONFIGDIR}/.kodi/addons/packages/${LATESTLIBRARYAUTOUPDATE}" -L "http://mirrors.kodi.tv/addons/leia/service.libraryautoupdate/${LATESTLIBRARYAUTOUPDATE}"
   unzip -q "${CONFIGDIR}/.kodi/addons/packages/${LATESTLIBRARYAUTOUPDATE}" -d "${CONFIGDIR}/.kodi/addons"

   chown -R abc:abc "${CONFIGDIR}"

fi