#!/bin/bash

echo "$(date '+%Y-%m-%d %H:%M:%S') INFO:    Correct owner, ${Puser_id}, Kodi shared user data, if required"
find "/usr/share/kodi/addons/" ! -user "${PUID}" -exec chown "${Puser_id}" {} \;
find "/usr/share/kodi/userdata/" ! -user "${PUID}" -exec chown "${Puser_id}" {} \;